import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:notey/features/notes/view/note_editor_screen.dart';

import 'helpers.dart';

void main() {
  setUp(() => setUpCommon());

  group('NoteEditorScreen', () {
    testWidgets('new note shows empty title and content fields',
        (WidgetTester tester) async {
      await tester.pumpWidget(buildTestApp(const NoteEditorScreen()));
      await tester.pumpAndSettle();

      expect(
        find.widgetWithText(TextField, 'عنوان الملاحظة...'),
        findsOneWidget,
      );
      expect(
        find.widgetWithText(TextField, 'اكتب تفاصيل ملاحظتك هنا...'),
        findsOneWidget,
      );
    });

    testWidgets('editing title and content works',
        (WidgetTester tester) async {
      await tester.pumpWidget(buildTestApp(const NoteEditorScreen()));
      await tester.pumpAndSettle();

      await tester.enterText(
        find.widgetWithText(TextField, 'عنوان الملاحظة...'),
        'عنوان جديد',
      );
      await tester.enterText(
        find.widgetWithText(TextField, 'اكتب تفاصيل ملاحظتك هنا...'),
        'محتوى جديد',
      );
      await tester.pump();

      expect(find.text('عنوان جديد'), findsOneWidget);
      expect(find.text('محتوى جديد'), findsOneWidget);
    });

    testWidgets('save button saves and pops back',
        (WidgetTester tester) async {
      await tester.pumpWidget(buildTestApp(const NoteEditorScreen()));
      await tester.pumpAndSettle();

      await tester.enterText(
        find.widgetWithText(TextField, 'عنوان الملاحظة...'),
        'ملاحظة محفوظة',
      );
      await tester.enterText(
        find.widgetWithText(TextField, 'اكتب تفاصيل ملاحظتك هنا...'),
        'تم الحفظ',
      );
      await tester.pump();

      await tester.tap(find.text('حفظ الملاحظة'));
      // SnackBar auto-dismiss (~4s) + route pop animation (~300ms)
      await tester.pump(const Duration(seconds: 5));

      // Editor should pop — the placeholder Scaffold behind it should now be visible
      expect(find.text('عنوان جديد'), findsNothing);
    });

    testWidgets('save without title shows error',
        (WidgetTester tester) async {
      await tester.pumpWidget(buildTestApp(const NoteEditorScreen()));
      await tester.pumpAndSettle();

      await tester.enterText(
        find.widgetWithText(TextField, 'اكتب تفاصيل ملاحظتك هنا...'),
        'محتوى فقط',
      );
      await tester.pump();

      await tester.tap(find.text('حفظ الملاحظة'));
      await tester.pumpAndSettle();

      expect(find.text('اكتب عنوانًا للملاحظة أولًا'), findsOneWidget);
    });

    testWidgets('editing existing note shows its title and content',
        (WidgetTester tester) async {
      final repo = FakeRepository();
      final note = await createTestNote(
        repo,
        title: 'ملاحظة قديمة',
        content: 'محتوى قديم',
      );

      await tester.pumpWidget(
        buildTestApp(NoteEditorScreen(note: note, repository: repo)),
      );
      await tester.pumpAndSettle();

      expect(find.text('ملاحظة قديمة'), findsOneWidget);
      expect(find.text('محتوى قديم'), findsOneWidget);
    });

    testWidgets('back button with unsaved changes shows dialog',
        (WidgetTester tester) async {
      await tester.pumpWidget(buildTestApp(const NoteEditorScreen()));
      await tester.pumpAndSettle();

      // Type something to create unsaved changes
      await tester.enterText(
        find.widgetWithText(TextField, 'عنوان الملاحظة...'),
        '喵',
      );
      await tester.pump();

      // Tap the AppBar back button (arrow_back icon generated by Flutter)
      await tester.tap(find.byIcon(Icons.arrow_back));
      await tester.pumpAndSettle();

      // Unsaved changes dialog should appear
      expect(find.text('تغييرات غير محفوظة'), findsOneWidget);
      expect(find.text('تجاهل'), findsOneWidget);
    });

    testWidgets('discard button discards changes',
        (WidgetTester tester) async {
      await tester.pumpWidget(buildTestApp(const NoteEditorScreen()));
      await tester.pumpAndSettle();

      await tester.enterText(
        find.widgetWithText(TextField, 'عنوان الملاحظة...'),
        '喵',
      );
      await tester.pump();

      await tester.tap(find.byIcon(Icons.arrow_back));
      await tester.pumpAndSettle();

      await tester.tap(find.text('تجاهل'));
      await tester.pumpAndSettle();

      // Should pop back to placeholder
      expect(find.text('喵'), findsNothing);
    });

    testWidgets('attachment button is present',
        (WidgetTester tester) async {
      await tester.pumpWidget(buildTestApp(const NoteEditorScreen()));
      await tester.pumpAndSettle();

      // The attachment add button exists in the editor body
      expect(find.text('إضافة مرفق'), findsOneWidget);
    });
  });
}
